#!/usr/bin/bash
[[ -z $ARCHUP_LOCAL ]] && ARCHUP_LOCAL=0
[[ -z $ARCHUP_NO_NETWORK ]] && ARCHUP_NO_NETWORK=0
[[ -z $ARCHUP_DAEMON ]] && ARCHUP_DAEMON=0
[[ -z $ARCHUP_MACHINE_NAME ]] && ARCHUP_MACHINE_NAME=box
[[ -z $ARCHUP_PACKAGES ]] && ARCHUP_PACKAGES=""
BASE_PACKAGES="systemd polkit"

usage()
{
    printf "USAGE: %s [OPTIONS] [packages...]\n" "$0"
    printf "\n"
    printf "OPTIONS:\n"
    printf "  -L                Local mode. Defaults to false.\n"
    printf "                    Use only local package databases and caches.\n"
    printf "  -N                Disable networking. Defaults to false.\n"
    printf "                    Set PrivateNetwork to true to\n"
    printf "                    forbidden the container to access networks.\n"
    printf "  -d                Run as daemon. Defaults to false.\n"
    printf "  -M machine-name   Set machine name. Defaults to \"box\".\n"
    printf "  -h                Show help and quit.\n"
}

while getopts LNdM:h option; do
    case $option in
        L) ARCHUP_LOCAL=1 ;;
        N) ARCHUP_NO_NETWORK=1 ;;
        d) ARCHUP_DAEMON=1 ;;
        M)
            if [[ -z $OPTARG ]]; then
                >&2 printf "Machine name cannot be empty."
                exit 1
            fi
            ARCHUP_MACHINE_NAME="$OPTARG"
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done
shift $(($OPTIND - 1))

ARCHUP_PACKAGES="$BASE_PACKAGES $ARCHUP_PACKAGES $*"

printf "%s: %s\n" LOCAL "$ARCHUP_LOCAL"
printf "%s: %s\n" NO_NETWORK "$ARCHUP_NO_NETWORK"
printf "%s: %s\n" DAEMON "$ARCHUP_DAEMON"
printf "%s: %s\n" MACHINE_NAME "$ARCHUP_MACHINE_NAME"
printf "%s: %s\n" PACKAGES "$ARCHUP_PACKAGES"

extra_flags=""
src="$(realpath .)"

if [[ $ARCHUP_LOCAL != 0 ]]; then
    extra_flags="$extra_flags -p BindReadOnlyPaths=$src/mirrorlist:/etc/pacman.d/mirrorlist"
else
    extra_flags="$extra_flags -p BindPaths=/var/lib/pacman/sync:/tmp/var/lib/pacman/sync"
fi

if [[ $ARCHUP_NO_NETWORK != 0 ]]; then
    extra_flags="$extra_flags -p PrivateNetwork=1"
fi

if [[ $ARCHUP_DAEMON == 0 ]]; then
    extra_flags="$extra_flags --tty"
fi

printf "flags: %s\n" "$extra_flags"

systemd-run \
    --collect \
    --unit "archup-$ARCHUP_MACHINE_NAME" \
    -p PrivateTmp=1 \
    -p RemoveIPC=1 \
    -p ProtectSystem=full \
    -p ProtectHome=1 \
    -p BindReadOnlyPaths=$src/pacman.conf:/etc/pacman.conf \
    -p BindReadOnlyPaths=$src/setup:/opt/archup \
    -p ReadWritePaths=/var/cache/pacman \
    -p ReadWritePaths=/var/lib/pacman/sync \
    -p ExecStop="/usr/bin/systemctl stop machine-\"$ARCHUP_MACHINE_NAME\".scope" \
    $extra_flags \
    /usr/bin/bash /opt/archup/setup.sh "$ARCHUP_MACHINE_NAME" $ARCHUP_PACKAGES

